# Generating Random Numbers (H1)

In [3]:
import numpy as np

In [4]:
r_1 = np.random.randint(1, 20, size=2)
print("Random integers (size 2):", r_1)

Random integers (size 2): [12  5]


In [5]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print("Random integers (1 row, 2 columns):")
print(r_2)

Random integers (1 row, 2 columns):
[[ 1 19]]


In [6]:
r_3 = np.random.rand(2, 1)
print("Random floats (2 rows, 1 column):")
print(r_3)

Random floats (2 rows, 1 column):
[[0.79880297]
 [0.24652589]]


In [7]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print("Random integers (4 rows, 5 columns):")
print(r_4)

Random integers (4 rows, 5 columns):
[[22 63 63 50 75]
 [28 87 67 39 56]
 [23 86 36 50 25]
 [36 44 22 54 48]]


In [8]:
r_5 = np.random.rand(4, 5)
print("Random integers (4 rows, 5 columns):")
print(r_5)

Random integers (4 rows, 5 columns):
[[0.61174999 0.36766526 0.46466086 0.63629632 0.51639647]
 [0.55668732 0.1707279  0.49863681 0.33910267 0.06284702]
 [0.03800209 0.5948388  0.18671159 0.49898144 0.34589865]
 [0.69448283 0.41812584 0.5507633  0.22787792 0.26402421]]


# Generating Random Choices from an Array

In [27]:
students = np.array(['Jordan', 'Vanessa', 'Craig', 'Rodolfo', 'Jaela', 'Mohammad', 'Zainab', 'Jen', 'Hassan',
                     'Symone','Martin','Caitlan'])
print("Students:", students)

Students: ['Jordan' 'Vanessa' 'Craig' 'Rodolfo' 'Jaela' 'Mohammad' 'Zainab' 'Jen'
 'Hassan' 'Symone' 'Martin' 'Caitlan']


In [21]:
call_on = np.random.choice(students)
print("Randomly selected student:", call_on)

Randomly selected student: Vanessa


In [26]:
breakout_groups = np.random.choice(students, size=(3, 4), replace=False)
print("Random breakout groups (3 rows, 4 columns):")
print(breakout_groups)

# This method can be an effective way to create random groups, that provides that there is no overlap if 'replace=false'

Random breakout groups (3 rows, 4 columns):
[['Symone' 'Rodolfo' 'Jordan' 'Zainab']
 ['Vanessa' 'Jen' 'Mohammad' 'Caitlan']
 ['Hassan' 'Martin' 'Armando' 'Craig']]


In [ ]:
students = np.array(['Jordan','Vanessa','Craig','Rodolfo','Jaela','Mohammad','Zainab','Jen','Hassan','Symone','Martin','Caitlan'])

In [28]:
probabilities = [0.05, 0.06, 0.02, 0.05, 0.07, 0.1, 0.08, 0.3, 0.07, 0.11, 0.09, 0.00]

In [29]:
call_on_weighted = np.random.choice(students, size=5, p=probabilities, replace=True)
print("Randomly selected students with weighted probabilities:", call_on_weighted)

Randomly selected students with weighted probabilities: ['Jen' 'Vanessa' 'Hassan' 'Rodolfo' 'Jen']


# Generating a Normal Distribution

In [30]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print("Bell curve with mean 10, standard deviation 5:")
print(bell_curve)

Bell curve with mean 10, standard deviation 5:
[[ 9.20259356  2.14907993  4.6536831   6.02025633  9.34637583]
 [13.44003184 12.95850874 12.85057745  5.40720654  8.55422938]
 [19.58364526  6.98553667 13.27102159  6.15411737  3.49119546]
 [ 9.77982967 15.71352472 -0.99145229 10.50780356  2.96681246]]
